---
image: debian:bookworm

stages:
  - code_quality

code_quality:
  stage: code_quality
  before_script:
    - apt-get update && apt-get -y install make
    - make install
    - make venv
  script:
    - . venv/bin/activate && make coverage
    - . venv/bin/activate && make lint
