---
image: debian:bookworm

stages:
  - code_quality

variables:
  GIT_STRATEGY: clone

code_quality:
  stage: code_quality
  before_script:
    - python3 -m venv venv
    - venv/bin/pip install -U pip
    - venv/bin/pip install -r requirements.lock
  script:
    - . venv/bin/activate && PYTEST_SLOW=1 make coverage
    - . venv/bin/activate && make lint
